[dependencies]
solana-client = "1.18.6"
solana-sdk = "1.18.6"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"
log = "0.4"
env_logger = "0.10"
